const translations: Record<string, Record<string, string>> = {
  en: {
    unlock_premium: "Unlock Premium Scripts",
    complete_1_task: "Complete 1 task to get",
    complete_task: "Complete the task to get",
    complete_final_task: "Complete the Final Task to get",
    checking_completion: "Complete the task",
    task_in_progress: "Task in progress",
    final_task: "Final Task!",
    final_task_title: "Final Task",
    loading_offers: "Loading offers...",
    failed_to_load: "Failed to load offers",
    try_again: "Try again",
    reward: "Reward:",
    start_task: "Start task",
    no_offers: "No offers available",
    refresh: "Refresh",
    very_easy: "VERY EASY",
    easy: "EASY",
    medium: "MEDIUM",
    tasks_completed: "Tasks Completed:",
    complete_3_tasks: "Complete 3 easy tasks to download your",
    task_completed: "Task Completed",
    all_tasks_completed: "All Tasks Completed! 🎉",
    download_scripts: "Download Premium Scripts",
    instantly: "instantly",
  },
  es: {
    unlock_premium: "Desbloquea Scripts Premium",
    complete_1_task: "Completa 1 tarea para obtener",
    complete_task: "Completa la tarea para obtener",
    complete_final_task: "Completa la Tarea Final para obtener",
    checking_completion: "Completa la tarea",
    task_in_progress: "Tarea en progreso",
    final_task: "¡Tarea Final!",
    final_task_title: "Tarea Final",
    loading_offers: "Cargando ofertas...",
    failed_to_load: "Error al cargar ofertas",
    try_again: "Intentar de nuevo",
    reward: "Recompensa:",
    start_task: "Comenzar tarea",
    no_offers: "No hay ofertas disponibles",
    refresh: "Actualizar",
    very_easy: "MUY FÁCIL",
    easy: "FÁCIL",
    medium: "MEDIO",
    tasks_completed: "Tareas Completadas:",
    complete_3_tasks: "Completa 3 tareas fáciles para descargar tu",
    task_completed: "Tarea Completada",
    all_tasks_completed: "¡Todas las Tareas Completadas! 🎉",
    download_scripts: "Descargar Scripts Premium",
    instantly: "instantáneamente",
  },
  fr: {
    unlock_premium: "Déverrouiller les scripts premium",
    complete_1_task: "Complétez 1 tâche pour obtenir",
    complete_task: "Complétez la tâche pour obtenir",
    complete_final_task: "Complétez la Tâche Finale pour obtenir",
    checking_completion: "Complétez la tâche",
    task_in_progress: "Tâche en cours",
    final_task: "Tâche Finale!",
    final_task_title: "Tâche Finale",
    loading_offers: "Chargement des offres...",
    failed_to_load: "Erreur lors du chargement des offres",
    try_again: "Réessayer",
    reward: "Récompense:",
    start_task: "Commencer la tâche",
    no_offers: "Aucune offre disponible",
    refresh: "Actualiser",
    very_easy: "TRÈS FACILE",
    easy: "FACILE",
    medium: "MOYEN",
    tasks_completed: "Tâches Complétées:",
    complete_3_tasks: "Complétez 3 tâches faciles pour télécharger votre",
    task_completed: "Tâche Complétée",
    all_tasks_completed: "Toutes les Tâches Complétées! 🎉",
    download_scripts: "Télécharger les Scripts Premium",
    instantly: "instantanément",
  },
  de: {
    unlock_premium: "Premium-Skripte freischalten",
    complete_1_task: "Schließen Sie 1 Aufgabe ab, um zu erhalten",
    complete_task: "Schließen Sie die Aufgabe ab, um zu erhalten",
    complete_final_task: "Schließen Sie die abschließende Aufgabe ab, um zu erhalten",
    checking_completion: "Schließen Sie die Aufgabe ab",
    task_in_progress: "Aufgabe läuft",
    final_task: "Abschließende Aufgabe!",
    final_task_title: "Abschließende Aufgabe",
    loading_offers: "Angebote werden geladen...",
    failed_to_load: "Fehler beim Laden von Angeboten",
    try_again: "Erneut versuchen",
    reward: "Belohnung:",
    start_task: "Aufgabe starten",
    no_offers: "Keine Angebote verfügbar",
    refresh: "Aktualisieren",
    very_easy: "SEHR EINFACH",
    easy: "EINFACH",
    medium: "MITTEL",
    tasks_completed: "Aufgaben Abgeschlossen:",
    complete_3_tasks: "Schließen Sie 3 einfache Aufgaben ab, um Ihre",
    task_completed: "Aufgabe Abgeschlossen",
    all_tasks_completed: "Alle Aufgaben Abgeschlossen! 🎉",
    download_scripts: "Premium-Skripte Herunterladen",
    instantly: "sofort",
  },
  pt: {
    unlock_premium: "Desbloquear Scripts Premium",
    complete_1_task: "Complete 1 tarefa para obter",
    complete_task: "Complete a tarefa para obter",
    complete_final_task: "Complete a Tarefa Final para obter",
    checking_completion: "Complete a tarefa",
    task_in_progress: "Tarefa em progresso",
    final_task: "Tarefa Final!",
    final_task_title: "Tarefa Final",
    loading_offers: "Carregando ofertas...",
    failed_to_load: "Erro ao carregar ofertas",
    try_again: "Tentar novamente",
    reward: "Recompensa:",
    start_task: "Iniciar tarefa",
    no_offers: "Nenhuma oferta disponível",
    refresh: "Atualizar",
    very_easy: "MUITO FÁCIL",
    easy: "FÁCIL",
    medium: "MÉDIO",
    tasks_completed: "Tarefas Concluídas:",
    complete_3_tasks: "Conclua 3 tarefas fáceis para baixar seu",
    task_completed: "Tarefa Concluída",
    all_tasks_completed: "Todas as Tarefas Concluídas! 🎉",
    download_scripts: "Baixar Scripts Premium",
    instantly: "instantaneamente",
  },
  it: {
    unlock_premium: "Sblocca Script Premium",
    complete_1_task: "Completa 1 attività per ottenere",
    complete_task: "Completa l'attività per ottenere",
    complete_final_task: "Completa l'Attività Finale per ottenere",
    checking_completion: "Completa l'attività",
    task_in_progress: "Attività in corso",
    final_task: "Attività Finale!",
    final_task_title: "Attività Finale",
    loading_offers: "Caricamento offerte...",
    failed_to_load: "Errore nel caricamento delle offerte",
    try_again: "Riprova",
    reward: "Ricompensa:",
    start_task: "Inizia attività",
    no_offers: "Nessuna offerta disponibile",
    refresh: "Aggiorna",
    very_easy: "MOLTO FACILE",
    easy: "FACILE",
    medium: "MEDIO",
    tasks_completed: "Attività Completate:",
    complete_3_tasks: "Completa 3 attività facili per scaricare il tuo",
    task_completed: "Attività Completata",
    all_tasks_completed: "Tutte le Attività Completate! 🎉",
    download_scripts: "Scarica Script Premium",
    instantly: "istantaneamente",
  },
  ru: {
    unlock_premium: "Разблокировать премиум-скрипты",
    complete_1_task: "Выполните 1 задачу, чтобы получить",
    complete_task: "Выполните задачу, чтобы получить",
    complete_final_task: "Выполните финальную задачу, чтобы получить",
    checking_completion: "Выполните задачу",
    task_in_progress: "Задача выполняется",
    final_task: "Финальная задача!",
    final_task_title: "Финальная задача",
    loading_offers: "Загрузка предложений...",
    failed_to_load: "Ошибка при загрузке предложений",
    try_again: "Попробовать снова",
    reward: "Награда:",
    start_task: "Начать задачу",
    no_offers: "Нет доступных предложений",
    refresh: "Обновить",
    very_easy: "ОЧЕНЬ ЛЕГКО",
    easy: "ЛЕГКО",
    medium: "СРЕДНЕ",
    tasks_completed: "Выполненные Задачи:",
    complete_3_tasks: "Выполните 3 простые задачи, чтобы загрузить",
    task_completed: "Задача Выполнена",
    all_tasks_completed: "Все Задачи Выполнены! 🎉",
    download_scripts: "Скачать Премиум-Скрипты",
    instantly: "мгновенно",
  },
  ja: {
    unlock_premium: "プレミアムスクリプトをアンロック",
    complete_1_task: "1つのタスクを完了して取得",
    complete_task: "タスクを完了して取得",
    complete_final_task: "最終タスクを完了して取得",
    checking_completion: "タスクを完了してください",
    task_in_progress: "タスク進行中",
    final_task: "最終タスク!",
    final_task_title: "最終タスク",
    loading_offers: "オファーを読み込み中...",
    failed_to_load: "オファーの読み込みに失敗しました",
    try_again: "もう一度試す",
    reward: "報酬:",
    start_task: "タスクを開始",
    no_offers: "利用可能なオファーはありません",
    refresh: "更新",
    very_easy: "非常に簡単",
    easy: "簡単",
    medium: "中程度",
    tasks_completed: "完了したタスク:",
    complete_3_tasks: "3つの簡単なタスクを完了してダウンロード",
    task_completed: "タスク完了",
    all_tasks_completed: "すべてのタスクが完了しました! 🎉",
    download_scripts: "プレミアムスクリプトをダウンロード",
    instantly: "すぐに",
  },
  zh: {
    unlock_premium: "解锁高级脚本",
    complete_1_task: "完成1个任务以获取",
    complete_task: "完成任务以获取",
    complete_final_task: "完成最终任务以获取",
    checking_completion: "完成任务",
    task_in_progress: "任务进行中",
    final_task: "最终任务!",
    final_task_title: "最终任务",
    loading_offers: "加载优惠...",
    failed_to_load: "加载优惠失败",
    try_again: "重试",
    reward: "奖励:",
    start_task: "开始任务",
    no_offers: "没有可用的优惠",
    refresh: "刷新",
    very_easy: "非常简单",
    easy: "简单",
    medium: "中等",
    tasks_completed: "已完成任务:",
    complete_3_tasks: "完成3个简单任务以下载您的",
    task_completed: "任务已完成",
    all_tasks_completed: "所有任务已完成! 🎉",
    download_scripts: "下载高级脚本",
    instantly: "立即",
  },
  ar: {
    unlock_premium: "فتح البرامج النصية المميزة",
    complete_1_task: "أكمل مهمة واحدة للحصول على",
    complete_task: "أكمل المهمة للحصول على",
    complete_final_task: "أكمل المهمة النهائية للحصول على",
    checking_completion: "أكمل المهمة",
    task_in_progress: "المهمة قيد التقدم",
    final_task: "المهمة النهائية!",
    final_task_title: "المهمة النهائية",
    loading_offers: "جاري تحميل العروض...",
    failed_to_load: "فشل تحميل العروض",
    try_again: "حاول مرة أخرى",
    reward: "المكافأة:",
    start_task: "ابدأ المهمة",
    no_offers: "لا توجد عروض متاحة",
    refresh: "تحديث",
    very_easy: "سهل جداً",
    easy: "سهل",
    medium: "متوسط",
    tasks_completed: "المهام المكتملة:",
    complete_3_tasks: "أكمل 3 مهام سهلة لتحميل",
    task_completed: "تم إكمال المهمة",
    all_tasks_completed: "تم إكمال جميع المهام! 🎉",
    download_scripts: "تحميل البرامج النصية المميزة",
    instantly: "فوراً",
  },
  ko: {
    unlock_premium: "프리미엄 스크립트 잠금 해제",
    complete_1_task: "1개의 작업을 완료하여 획득",
    complete_task: "작업을 완료하여 획득",
    complete_final_task: "최종 작업을 완료하여 획득",
    checking_completion: "작업을 완료하세요",
    task_in_progress: "작업 진행 중",
    final_task: "최종 작업!",
    final_task_title: "최종 작업",
    loading_offers: "오퍼 로드 중...",
    failed_to_load: "오퍼 로드 실패",
    try_again: "다시 시도",
    reward: "보상:",
    start_task: "작업 시작",
    no_offers: "사용 가능한 오퍼 없음",
    refresh: "새로고침",
    very_easy: "매우 쉬움",
    easy: "쉬움",
    medium: "중간",
    tasks_completed: "완료된 작업:",
    complete_3_tasks: "3가지 간단한 작업을 완료하여 다운로드",
    task_completed: "작업 완료됨",
    all_tasks_completed: "모든 작업이 완료되었습니다! 🎉",
    download_scripts: "프리미엄 스크립트 다운로드",
    instantly: "즉시",
  },
  th: {
    unlock_premium: "ปลดล็อกสคริปต์พรีเมียม",
    complete_1_task: "ทำงาน 1 งานให้เสร็จเพื่อรับ",
    complete_task: "ทำงานให้เสร็จเพื่อรับ",
    complete_final_task: "ทำงานสุดท้ายให้เสร็จเพื่อรับ",
    checking_completion: "ทำงานให้เสร็จ",
    task_in_progress: "งานกำลังดำเนินการ",
    final_task: "งานสุดท้าย!",
    final_task_title: "งานสุดท้าย",
    loading_offers: "กำลังโหลดข้อเสนอ...",
    failed_to_load: "ไม่สามารถโหลดข้อเสนอ",
    try_again: "ลองอีกครั้ง",
    reward: "รางวัล:",
    start_task: "เริ่มงาน",
    no_offers: "ไม่มีข้อเสนอที่พร้อมใช้งาน",
    refresh: "รีเฟรช",
    very_easy: "ง่ายมาก",
    easy: "ง่าย",
    medium: "ปานกลาง",
    tasks_completed: "งานที่เสร็จแล้ว:",
    complete_3_tasks: "ทำงาน 3 งานให้เสร็จเพื่อดาวน์โหลด",
    task_completed: "เสร็จสิ้นงาน",
    all_tasks_completed: "ทำงานทั้งหมดให้เสร็จแล้ว! 🎉",
    download_scripts: "ดาวน์โหลดสคริปต์พรีเมียม",
    instantly: "ทันที",
  },
  vi: {
    unlock_premium: "Mở khóa Tập lệnh Premium",
    complete_1_task: "Hoàn thành 1 nhiệm vụ để nhận",
    complete_task: "Hoàn thành nhiệm vụ để nhận",
    complete_final_task: "Hoàn thành Nhiệm vụ Cuối cùng để nhận",
    checking_completion: "Hoàn thành nhiệm vụ",
    task_in_progress: "Nhiệm vụ đang tiến hành",
    final_task: "Nhiệm vụ Cuối cùng!",
    final_task_title: "Nhiệm vụ Cuối cùng",
    loading_offers: "Đang tải các ưu đãi...",
    failed_to_load: "Không thể tải các ưu đãi",
    try_again: "Thử lại",
    reward: "Phần thưởng:",
    start_task: "Bắt đầu nhiệm vụ",
    no_offers: "Không có ưu đãi nào",
    refresh: "Làm mới",
    very_easy: "RẤT DỄ",
    easy: "DỄ",
    medium: "TRUNG BÌNH",
    tasks_completed: "Nhiệm vụ đã hoàn thành:",
    complete_3_tasks: "Hoàn thành 3 nhiệm vụ dễ dàng để tải xuống",
    task_completed: "Nhiệm vụ Hoàn thành",
    all_tasks_completed: "Tất cả các Nhiệm vụ đã Hoàn thành! 🎉",
    download_scripts: "Tải xuống Tập lệnh Premium",
    instantly: "ngay lập tức",
  },
  id: {
    unlock_premium: "Buka Kunci Skrip Premium",
    complete_1_task: "Selesaikan 1 tugas untuk mendapatkan",
    complete_task: "Selesaikan tugas untuk mendapatkan",
    complete_final_task: "Selesaikan Tugas Akhir untuk mendapatkan",
    checking_completion: "Selesaikan tugas",
    task_in_progress: "Tugas sedang berlangsung",
    final_task: "Tugas Akhir!",
    final_task_title: "Tugas Akhir",
    loading_offers: "Memuat penawaran...",
    failed_to_load: "Gagal memuat penawaran",
    try_again: "Coba lagi",
    reward: "Hadiah:",
    start_task: "Mulai tugas",
    no_offers: "Tidak ada penawaran tersedia",
    refresh: "Segarkan",
    very_easy: "SANGAT MUDAH",
    easy: "MUDAH",
    medium: "SEDANG",
    tasks_completed: "Tugas Selesai:",
    complete_3_tasks: "Selesaikan 3 tugas mudah untuk mengunduh",
    task_completed: "Tugas Selesai",
    all_tasks_completed: "Semua Tugas Selesai! 🎉",
    download_scripts: "Unduh Skrip Premium",
    instantly: "segera",
  },
  pl: {
    unlock_premium: "Odblokuj Skrypty Premium",
    complete_1_task: "Ukończ 1 zadanie, aby uzyskać",
    complete_task: "Ukończ zadanie, aby uzyskać",
    complete_final_task: "Ukończ Zadanie Końcowe, aby uzyskać",
    checking_completion: "Ukończ zadanie",
    task_in_progress: "Zadanie w toku",
    final_task: "Zadanie Końcowe!",
    final_task_title: "Zadanie Końcowe",
    loading_offers: "Ładowanie ofert...",
    failed_to_load: "Nie udało się załadować ofert",
    try_again: "Spróbuj ponownie",
    reward: "Nagroda:",
    start_task: "Rozpocznij zadanie",
    no_offers: "Brak dostępnych ofert",
    refresh: "Odśwież",
    very_easy: "BARDZO ŁATWE",
    easy: "ŁATWE",
    medium: "ŚREDNIE",
    tasks_completed: "Ukończone Zadania:",
    complete_3_tasks: "Ukończ 3 łatwe zadania, aby pobrać",
    task_completed: "Zadanie Ukończone",
    all_tasks_completed: "Wszystkie Zadania Ukończone! 🎉",
    download_scripts: "Pobierz Premium Skrypty",
    instantly: "natychmiast",
  },
  tr: {
    unlock_premium: "Premium Komut Dosyalarının Kilidini Aç",
    complete_1_task: "Almak için 1 görevi tamamlayın",
    complete_task: "Almak için görevi tamamlayın",
    complete_final_task: "Almak için Son Görevi tamamlayın",
    checking_completion: "Görevi tamamlayın",
    task_in_progress: "Görev devam ediyor",
    final_task: "Son Görev!",
    final_task_title: "Son Görev",
    loading_offers: "Teklifler yükleniyor...",
    failed_to_load: "Teklifler yüklenemedi",
    try_again: "Tekrar deneyin",
    reward: "Ödül:",
    start_task: "Görevi başlat",
    no_offers: "Kullanılabilir teklif yok",
    refresh: "Yenile",
    very_easy: "ÇOK KOLAY",
    easy: "KOLAY",
    medium: "ORTA",
    tasks_completed: "Tamamlanan Görevler:",
    complete_3_tasks: "3 kolay görevi tamamlayın ve indirin",
    task_completed: "Görev Tamamlandı",
    all_tasks_completed: "Tüm Görevler Tamamlandı! 🎉",
    download_scripts: "Premium Komut Dosyalarını İndir",
    instantly: "hemen",
  },
  nl: {
    unlock_premium: "Premium Scripts ontgrendelen",
    complete_1_task: "Voltooi 1 taak om te krijgen",
    complete_task: "Voltooi de taak om te krijgen",
    complete_final_task: "Voltooi de Eindtaak om te krijgen",
    checking_completion: "Voltooi de taak",
    task_in_progress: "Taak in uitvoering",
    final_task: "Eindtaak!",
    final_task_title: "Eindtaak",
    loading_offers: "Aanbiedingen laden...",
    failed_to_load: "Aanbiedingen kunnen niet worden geladen",
    try_again: "Probeer opnieuw",
    reward: "Beloning:",
    start_task: "Taak starten",
    no_offers: "Geen aanbiedingen beschikbaar",
    refresh: "Vernieuwen",
    very_easy: "ZEER GEMAKKELIJK",
    easy: "GEMAKKELIJK",
    medium: "GEMIDDELD",
    tasks_completed: "Voltooide Taken:",
    complete_3_tasks: "Voltooi 3 eenvoudige taken om te downloaden",
    task_completed: "Taak Voltooid",
    all_tasks_completed: "Alle Taken Voltooid! 🎉",
    download_scripts: "Premium Scripts Downloaden",
    instantly: "direct",
  },
  sv: {
    unlock_premium: "Lås upp Premium-skript",
    complete_1_task: "Fullför 1 uppgift för att få",
    complete_task: "Fullför uppgiften för att få",
    complete_final_task: "Fullför den sista uppgiften för att få",
    checking_completion: "Fullför uppgiften",
    task_in_progress: "Uppgift pågår",
    final_task: "Slutlig uppgift!",
    final_task_title: "Slutlig uppgift",
    loading_offers: "Läser in erbjudanden...",
    failed_to_load: "Det gick inte att läsa in erbjudanden",
    try_again: "Försök igen",
    reward: "Belöning:",
    start_task: "Starta uppgift",
    no_offers: "Inga erbjudanden tillgängliga",
    refresh: "Uppdatera",
    very_easy: "MYCKET LÄTT",
    easy: "LÄTT",
    medium: "MEDEL",
    tasks_completed: "Slutförda Uppgifter:",
    complete_3_tasks: "Slutför 3 enkla uppgifter för att ladda ner",
    task_completed: "Uppgift Slutförd",
    all_tasks_completed: "Alla Uppgifter Slutförda! 🎉",
    download_scripts: "Ladda ner Premium-skript",
    instantly: "omedelbar",
  },
  da: {
    unlock_premium: "Lås Premium-scripts op",
    complete_1_task: "Fuldfør 1 opgave for at få",
    complete_task: "Fuldfør opgaven for at få",
    complete_final_task: "Fuldfør den endelige opgave for at få",
    checking_completion: "Fuldfør opgaven",
    task_in_progress: "Opgave i gang",
    final_task: "Endelig opgave!",
    final_task_title: "Endelig opgave",
    loading_offers: "Indlæser tilbud...",
    failed_to_load: "Kunne ikke indlæse tilbud",
    try_again: "Prøv igen",
    reward: "Belønning:",
    start_task: "Start opgave",
    no_offers: "Ingen tilbud tilgængelige",
    refresh: "Opdater",
    very_easy: "MEGET NEMT",
    easy: "NEMT",
    medium: "MEDIUM",
    tasks_completed: "Fuldførte Opgaver:",
    complete_3_tasks: "Fuldfør 3 nemme opgaver for at hente",
    task_completed: "Opgave Fuldført",
    all_tasks_completed: "Alle Opgaver Fuldført! 🎉",
    download_scripts: "Download Premium-scripts",
    instantly: "øjeblikkeligt",
  },
  no: {
    unlock_premium: "Lås opp Premium-skript",
    complete_1_task: "Fullfør 1 oppgave for å få",
    complete_task: "Fullfør oppgaven for å få",
    complete_final_task: "Fullfør den siste oppgaven for å få",
    checking_completion: "Fullfør oppgaven",
    task_in_progress: "Oppgave pågår",
    final_task: "Siste oppgave!",
    final_task_title: "Siste oppgave",
    loading_offers: "Laster inn tilbud...",
    failed_to_load: "Kunne ikke laste inn tilbud",
    try_again: "Prøv igjen",
    reward: "Belønning:",
    start_task: "Start oppgave",
    no_offers: "Ingen tilbud tilgjengelig",
    refresh: "Oppdater",
    very_easy: "VELDIG LETT",
    easy: "LETT",
    medium: "MEDIUM",
    tasks_completed: "Fullførte Oppgaver:",
    complete_3_tasks: "Fullfør 3 enkle oppgaver for å laste ned",
    task_completed: "Oppgave Fullført",
    all_tasks_completed: "Alle Oppgaver Fullført! 🎉",
    download_scripts: "Last ned Premium-skript",
    instantly: "øyeblikkelig",
  },
  fi: {
    unlock_premium: "Avaa Premium-skriptit",
    complete_1_task: "Suorita 1 tehtävä saadaksesi",
    complete_task: "Suorita tehtävä saadaksesi",
    complete_final_task: "Suorita viimeinen tehtävä saadaksesi",
    checking_completion: "Suorita tehtävä",
    task_in_progress: "Tehtävä käynnissä",
    final_task: "Viimeinen tehtävä!",
    final_task_title: "Viimeinen tehtävä",
    loading_offers: "Ladataan tarjouksia...",
    failed_to_load: "Tarjousten lataaminen epäonnistui",
    try_again: "Yritä uudelleen",
    reward: "Palkinto:",
    start_task: "Aloita tehtävä",
    no_offers: "Ei saatavilla olevia tarjouksia",
    refresh: "Päivitä",
    very_easy: "ERITTÄIN HELPPO",
    easy: "HELPPO",
    medium: "MEDIUM",
    tasks_completed: "Suoritetut Tehtävät:",
    complete_3_tasks: "Suorita 3 helppoa tehtävää ladataksesi",
    task_completed: "Tehtävä Suoritettu",
    all_tasks_completed: "Kaikki Tehtävät Suoritettu! 🎉",
    download_scripts: "Lataa Premium-skriptit",
    instantly: "välittömästi",
  },
  cs: {
    unlock_premium: "Odemknout prémiové skripty",
    complete_1_task: "Dokončete 1 úkol, aby ste získali",
    complete_task: "Dokončete úkol, aby ste získali",
    complete_final_task: "Dokončete poslední úkol, aby ste získali",
    checking_completion: "Dokončete úkol",
    task_in_progress: "Úkol probíhá",
    final_task: "Poslední úkol!",
    final_task_title: "Poslední úkol",
    loading_offers: "Načítavajú sa ponuky...",
    failed_to_load: "Nepodarilo sa načítať ponuky",
    try_again: "Skúsiť znova",
    reward: "Odmena:",
    start_task: "Spustiť úkol",
    no_offers: "Nie sú k dispozícii žiadne ponuky",
    refresh: "Obnoviť",
    very_easy: "VEĽMI ĽAHKÉ",
    easy: "ĽAHKÉ",
    medium: "STREDNÍ",
    tasks_completed: "Dokončené úkoly:",
    complete_3_tasks: "Dokončite 3 jednoduché úkoly, aby ste stiahnuli",
    task_completed: "Úkol dokončený",
    all_tasks_completed: "Všetky úkoly dokončené! 🎉",
    download_scripts: "Stiahnuť prémiové skripty",
    instantly: "okamžite",
  },
  el: {
    unlock_premium: "Ξεκλείδωσε τα Premium Scripts",
    complete_1_task: "Ολοκληρώστε 1 εργασία για να λάβετε",
    complete_task: "Ολοκληρώστε την εργασία για να λάβετε",
    complete_final_task: "Ολοκληρώστε την τελική εργασία για να λάβετε",
    checking_completion: "Ολοκληρώστε την εργασία",
    task_in_progress: "Εργασία σε εξέλιξη",
    final_task: "Τελική εργασία!",
    final_task_title: "Τελική εργασία",
    loading_offers: "Φόρτωση προσφορών...",
    failed_to_load: "Αποτυχία φόρτωσης προσφορών",
    try_again: "Δοκιμάστε ξανά",
    reward: "Ανταμοιβή:",
    start_task: "Ξεκινήστε την εργασία",
    no_offers: "Δεν υπάρχουν διαθέσιμες προσφορές",
    refresh: "Ανανέωση",
    very_easy: "ΠΟΛΥ ΕΥΚΟΛΟ",
    easy: "ΕΥΚΟΛΟ",
    medium: "ΜΕΣΑΙΟ",
    tasks_completed: "Ολοκληρωμένες Εργασίες:",
    complete_3_tasks: "Ολοκληρώστε 3 εύκολες εργασίες για να κατεβάσετε",
    task_completed: "Εργασία Ολοκληρώθηκε",
    all_tasks_completed: "Όλες οι Εργασίες Ολοκληρώθηκαν! 🎉",
    download_scripts: "Κατεβάστε Premium Scripts",
    instantly: "αμέσως",
  },
  bg: {
    unlock_premium: "Отключи Премиум Скриптове",
    complete_1_task: "Завършете 1 задача, за да получите",
    complete_task: "Завършете задачата, за да получите",
    complete_final_task: "Завършете последната задача, за да получите",
    checking_completion: "Завършете задачата",
    task_in_progress: "Задачата е в ход",
    final_task: "Последната задача!",
    final_task_title: "Последната задача",
    loading_offers: "Зареждане на предложения...",
    failed_to_load: "Неуспешно зареждане на предложения",
    try_again: "Опитайте отново",
    reward: "Награда:",
    start_task: "Начало на задачата",
    no_offers: "Няма налични предложения",
    refresh: "Обновяване",
    very_easy: "МНОГО ЛЕСНО",
    easy: "ЛЕСНО",
    medium: "СРЕДНО",
    tasks_completed: "Завършени Задачи:",
    complete_3_tasks: "Завършете 3 лесни задачи, за да изтеглите",
    task_completed: "Задача Завършена",
    all_tasks_completed: "Всички Задачи Завършени! 🎉",
    download_scripts: "Изтегли Премиум Скриптове",
    instantly: "веднага",
  },
  hr: {
    unlock_premium: "Otključaj Premium Skripte",
    complete_1_task: "Završi 1 zadatak da bi dobio",
    complete_task: "Završi zadatak da bi dobio",
    complete_final_task: "Završi završni zadatak da bi dobio",
    checking_completion: "Završi zadatak",
    task_in_progress: "Zadatak je u tijeku",
    final_task: "Završni zadatak!",
    final_task_title: "Završni zadatak",
    loading_offers: "Učitavanje ponuda...",
    failed_to_load: "Neuspješno učitavanje ponuda",
    try_again: "Pokušaj ponovno",
    reward: "Nagrada:",
    start_task: "Započni zadatak",
    no_offers: "Nema dostupnih ponuda",
    refresh: "Osvježi",
    very_easy: "VRLO LAKO",
    easy: "LAKO",
    medium: "SREDNJE",
    tasks_completed: "Završeni Zadaci:",
    complete_3_tasks: "Završi 3 laka zadatka da bi preuzeo",
    task_completed: "Zadatak Završen",
    all_tasks_completed: "Svi Zadaci Završeni! 🎉",
    download_scripts: "Preuzmi Premium Skripte",
    instantly: "odmah",
  },
  sk: {
    unlock_premium: "Odomknúť prémiové skripty",
    complete_1_task: "Dokončite 1 úlohu, aby ste získali",
    complete_task: "Dokončite úlohu, aby ste získali",
    complete_final_task: "Dokončite finálnu úlohu, aby ste získali",
    checking_completion: "Dokončite úlohu",
    task_in_progress: "Úloha prebieha",
    final_task: "Finálna úloha!",
    final_task_title: "Finálna úloha",
    loading_offers: "Načítavajú sa ponuky...",
    failed_to_load: "Nepodarilo sa načítať ponuky",
    try_again: "Skúsiť znova",
    reward: "Odmena:",
    start_task: "Spustiť úlohu",
    no_offers: "Nie sú k dispozícii žiadne ponuky",
    refresh: "Obnoviť",
    very_easy: "VEĽMI ĽAHKÉ",
    easy: "ĽAHKÉ",
    medium: "STREDNÉ",
    tasks_completed: "Dokončené Úlohy:",
    complete_3_tasks: "Dokončite 3 jednoduché úlohy, aby ste stiahli",
    task_completed: "Úloha Dokončená",
    all_tasks_completed: "Všetky Úlohy Dokončené! 🎉",
    download_scripts: "Stiahnuť Prémiové Skripty",
    instantly: "okamžite",
  },
  ro: {
    unlock_premium: "Deblochează Scripturi Premium",
    complete_1_task: "Completează 1 sarcină pentru a obține",
    complete_task: "Completează sarcina pentru a obține",
    complete_final_task: "Completează sarcina finală pentru a obține",
    checking_completion: "Completează sarcina",
    task_in_progress: "Sarcina este în curs",
    final_task: "Sarcina finală!",
    final_task_title: "Sarcina finală",
    loading_offers: "Se încarcă ofertele...",
    failed_to_load: "Încărcarea ofertelor a eșuat",
    try_again: "Încearcă din nou",
    reward: "Recompensă:",
    start_task: "Începe sarcina",
    no_offers: "Nu sunt disponibile oferte",
    refresh: "Reîmprospătează",
    very_easy: "FOARTE UȘOR",
    easy: "UȘOR",
    medium: "MEDIU",
    tasks_completed: "Sarcini Finalizate:",
    complete_3_tasks: "Completează 3 sarcini ușoare pentru a descărca",
    task_completed: "Sarcina Finalizată",
    all_tasks_completed: "Toate Sarcinile Finalizate! 🎉",
    download_scripts: "Descarcă Scripturi Premium",
    instantly: "instant",
  },
  hu: {
    unlock_premium: "Oldjon fel prémium szkripteket",
    complete_1_task: "Végezzen el 1 feladatot a megszerzéshez",
    complete_task: "Végezzen el egy feladatot a megszerzéshez",
    complete_final_task: "Végezzen el egy végső feladatot a megszerzéshez",
    checking_completion: "Végezzen el egy feladatot",
    task_in_progress: "Feladat van folyamatban",
    final_task: "Végső feladat!",
    final_task_title: "Végső feladat",
    loading_offers: "Ajánlatok betöltése...",
    failed_to_load: "Az ajánlatok betöltése sikertelen",
    try_again: "Próbálja újra",
    reward: "Jutalom:",
    start_task: "Feladat indítása",
    no_offers: "Nincs elérhető ajánlat",
    refresh: "Frissítés",
    very_easy: "NAGYON KÖNNYŰ",
    easy: "KÖNNYŰ",
    medium: "KÖZEPES",
    tasks_completed: "Elvégzett Feladatok:",
    complete_3_tasks: "Végezzen el 3 könnyű feladatot a letöltéshez",
    task_completed: "Feladat Elvégezve",
    all_tasks_completed: "Minden Feladat Elvégezve! 🎉",
    download_scripts: "Töltse le a prémium szkripteket",
    instantly: "azonnal",
  },
}

export function getTranslation(language: string, key: string): string {
  console.log("[v0] getTranslation called with:", { language, key })

  let lang = translations[language as keyof typeof translations]

  if (!lang) {
    lang = translations.en
  }

  const result = lang[key as keyof typeof lang] || translations.en[key as keyof typeof translations.en] || key
  console.log("[v0] Translation result:", result)
  return result
}

export async function detectCountryAndGetLanguage(): Promise<string> {
  try {
    const response = await fetch("https://ipwho.is/")
    const data = await response.json()
    const countryCode = data.country_code?.toLowerCase() || "us"

    console.log("[v0] Detected country code:", countryCode)

    const countryToLanguage: Record<string, string> = {
      // Africa
      dz: "ar",
      za: "en",
      ao: "pt",
      bj: "fr",
      bw: "en",
      bf: "fr",
      bi: "fr",
      cm: "fr",
      cv: "pt",
      cf: "fr",
      td: "fr",
      km: "fr",
      cg: "fr",
      cd: "fr",
      ci: "fr",
      dj: "ar",
      eg: "ar",
      gq: "es",
      er: "ar",
      et: "en",
      ga: "fr",
      gm: "en",
      gh: "en",
      gn: "fr",
      gw: "pt",
      ke: "en",
      ls: "en",
      lr: "en",
      ly: "ar",
      mg: "fr",
      mw: "en",
      ml: "fr",
      mr: "ar",
      mu: "en",
      ma: "ar",
      mz: "pt",
      na: "en",
      ne: "fr",
      ng: "en",
      rw: "en",
      st: "pt",
      sn: "fr",
      sc: "en",
      sl: "en",
      so: "ar",
      ss: "en",
      sd: "ar",
      sz: "en",
      tz: "en",
      ug: "en",
      zm: "en",
      zw: "en",

      // Americas
      ag: "en",
      ai: "en",
      aw: "nl",
      bs: "en",
      bb: "en",
      bz: "en",
      bm: "en",
      bo: "es",
      br: "pt",
      ca: "en",
      ky: "en",
      cl: "es",
      co: "es",
      cr: "es",
      cu: "es",
      dm: "en",
      do: "es",
      ec: "es",
      sv: "es",
      fk: "en",
      gf: "fr",
      gd: "en",
      gp: "fr",
      gt: "es",
      gy: "en",
      ht: "fr",
      hn: "es",
      jm: "en",
      mq: "fr",
      mx: "es",
      ms: "en",
      ni: "es",
      pa: "es",
      py: "es",
      pe: "es",
      kn: "en",
      lc: "en",
      vc: "en",
      sr: "nl",
      tc: "en",
      tt: "en",
      us: "en",
      uy: "es",
      ve: "es",
      vg: "en",
      vi: "en",

      // Asia
      af: "ar",
      az: "ru",
      bh: "ar",
      bd: "en",
      bt: "en",
      bn: "en",
      kh: "en",
      cn: "zh",
      hk: "zh",
      in: "en",
      id: "id",
      ir: "ar",
      iq: "ar",
      il: "en",
      jp: "ja",
      jo: "ar",
      kz: "ru",
      kp: "ko",
      kr: "ko",
      kw: "ar",
      kg: "ru",
      la: "en",
      lb: "ar",
      mo: "zh",
      my: "id",
      mv: "en",
      mn: "en",
      mm: "en",
      np: "en",
      om: "ar",
      pk: "en",
      ph: "id",
      qa: "ar",
      sa: "ar",
      sg: "zh",
      lk: "en",
      sy: "ar",
      tw: "zh",
      tj: "ru",
      th: "th",
      tl: "en",
      tr: "tr",
      tm: "ru",
      ae: "ar",
      uz: "ru",
      vn: "vi",
      ye: "ar",

      // Europe
      al: "en",
      ad: "es",
      at: "de",
      by: "ru",
      be: "nl",
      ba: "en",
      bg: "bg",
      hr: "hr",
      cy: "el",
      cz: "cs",
      dk: "da",
      ee: "en",
      fi: "fi",
      fr: "fr",
      de: "de",
      gr: "el",
      hu: "hu",
      is: "en",
      ie: "en",
      it: "it",
      xk: "en",
      lv: "en",
      li: "de",
      lt: "en",
      lu: "fr",
      mt: "en",
      md: "en",
      mc: "fr",
      me: "en",
      nl: "nl",
      no: "no",
      pl: "pl",
      pt: "pt",
      ro: "ro",
      ru: "ru",
      sm: "it",
      rs: "en",
      sk: "sk",
      si: "en",
      es: "es",
      se: "sv",
      ch: "de",
      ua: "ru",
      gb: "en",
      va: "it",

      // Oceania
      au: "en",
      fj: "en",
      ki: "en",
      mh: "en",
      fm: "en",
      nr: "en",
      nz: "en",
      pw: "en",
      pg: "en",
      sb: "en",
      to: "en",
      tv: "en",
      vu: "en",
      ws: "en",

      // Other territories
      ax: "sv",
      bq: "nl",
      sx: "nl",
      cw: "nl",
      je: "en",
      gg: "en",
      im: "en",
      pm: "fr",
      re: "fr",
      bl: "fr",
      mf: "fr",
      wf: "fr",
      pf: "fr",
      nc: "fr",
      gi: "en",
      gs: "en",
      io: "en",
      um: "en",
      fo: "da",
      gl: "da",
    }

    const detectedLanguage = countryToLanguage[countryCode] || "en"
    console.log("[v0] Detected language:", detectedLanguage)
    return detectedLanguage
  } catch (error) {
    console.log("[v0] Error detecting language:", error)
    if (typeof window !== "undefined" && window.navigator.language) {
      const browserLang = window.navigator.language.split("-")[0].toLowerCase()
      const languageMap: Record<string, string> = {
        bg: "bg",
        de: "de",
        fr: "fr",
        es: "es",
        it: "it",
        pt: "pt",
        nl: "nl",
        pl: "pl",
        ru: "ru",
        ja: "ja",
        zh: "zh",
        ko: "ko",
        ar: "ar",
        th: "th",
        vi: "vi",
        id: "id",
        tr: "tr",
        sv: "sv",
        da: "da",
        no: "no",
        fi: "fi",
        cs: "cs",
        el: "el",
        hr: "hr",
        sk: "sk",
        ro: "ro",
        hu: "hu",
      }
      const browserDetectedLang = languageMap[browserLang] || "en"
      console.log("[v0] Fallback to browser language:", browserDetectedLang)
      return browserDetectedLang
    }
    console.log("[v0] Defaulting to English")
    return "en"
  }
}
